baseURL: "https://youngandpowerful.sg/"
languageCode: "en-us"
title: "Young & Powerful"
permalinks:
  post: /:title/
taxonomies:
  category: "categories"
  tag: "tags"
paginate: 10
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
author:
    name: "Young & Powerful Singapore"
    email: "hello@youngandpowerful.sg"